-- rambler up
DROP EXTENSION IF EXISTS citext;
CREATE EXTENSION citext;

DO $$ BEGIN
  IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='apiuser') THEN
    CREATE ROLE apiuser NOINHERIT;
  END IF;
  IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='readonly') THEN
    CREATE ROLE readonly NOINHERIT;
  END IF;
END $$;
GRANT apiuser TO postgres;
GRANT USAGE ON SCHEMA public TO apiuser;
ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO apiuser;
ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT ALL PRIVILEGES ON SEQUENCES TO apiuser;
GRANT USAGE ON SCHEMA public TO readonly;
ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES
IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO readonly;
-- rambler down
